# Generated by Django 5.2.14 on 2026-05-14 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_id', models.CharField(max_length=120, unique=True)),
                ('task_type', models.CharField(choices=[('task1_academic', 'Task 1 Academic'), ('task2', 'Task 2')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('prompt', models.TextField()),
                ('source', models.CharField(default='local_seed', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['task_type', 'is_active'], name='writing_wri_task_ty_306476_idx')],
            },
        ),
        migrations.CreateModel(
            name='WritingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_entry_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('task_type', models.CharField(choices=[('task1_academic', 'Task 1 Academic'), ('task2', 'Task 2')], max_length=32)),
                ('practice_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('prompt_text', models.TextField()),
                ('answer', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('scored', 'Scored')], default='saved', max_length=24)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_entries', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='writing.writingprompt')),
            ],
        ),
        migrations.CreateModel(
            name='WritingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task_response', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('coherence_cohesion', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('lexical_resource', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('grammar_range_accuracy', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('feedback_markdown', models.TextField(blank=True)),
                ('grammar_corrections', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='ai', max_length=32)),
                ('billing_metadata', models.JSONField(blank=True, default=dict)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='writing.writingentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='writingentry',
            index=models.Index(fields=['user', 'created_at'], name='writing_wri_user_id_ef03cf_idx'),
        ),
        migrations.AddIndex(
            model_name='writingentry',
            index=models.Index(fields=['user', 'practice_date'], name='writing_wri_user_id_b6bd27_idx'),
        ),
        migrations.AddIndex(
            model_name='writingentry',
            index=models.Index(fields=['user', 'task_type', 'created_at'], name='writing_wri_user_id_f1fece_idx'),
        ),
        migrations.AddIndex(
            model_name='writingscore',
            index=models.Index(fields=['user', 'created_at'], name='writing_wri_user_id_436f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='writingscore',
            index=models.Index(fields=['overall_band', 'created_at'], name='writing_wri_overall_d50d24_idx'),
        ),
    ]
