# Generated by Django 5.2.14 on 2026-05-14 14:48

import hashlib

from django.db import migrations, models


def populate_entry_ids(apps, schema_editor):
    WritingEntry = apps.get_model("writing", "WritingEntry")
    for entry in WritingEntry.objects.all().order_by("pk"):
        base = entry.legacy_entry_id or f"writing-entry-{entry.pk}"
        digest = hashlib.sha1(f"{entry.pk}:{base}".encode("utf-8")).hexdigest()[:20]
        entry.entry_id = str(entry.legacy_entry_id or f"entry_{digest}")[:80]
        entry.save(update_fields=["entry_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_writinglearnerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingentry',
            name='entry_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.RunPython(populate_entry_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='writingentry',
            name='entry_id',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
    ]
