# Generated by Django 5.2.14 on 2026-05-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_writingentry_entry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingprompt',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
