# Generated by Django 5.2.14 on 2026-05-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0005_writingprompt_source_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingscore',
            name='analysis_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
