# Generated by Django 5.2.14 on 2026-06-03 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0007_writingprompt_chart_facts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellingDrillWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word_id', models.CharField(max_length=64)),
                ('correct_spelling', models.CharField(max_length=120)),
                ('normalized', models.CharField(max_length=120)),
                ('wrong_forms', models.JSONField(blank=True, default=list)),
                ('chinese_gloss', models.CharField(blank=True, max_length=200)),
                ('explanation', models.TextField(blank=True)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('mastered', 'Mastered'), ('dismissed', 'Dismissed')], default='active', max_length=24)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('source_refs', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spelling_drill_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status', 'last_practiced_at'], name='writing_spe_user_id_9ce221_idx'), models.Index(fields=['user', 'updated_at'], name='writing_spe_user_id_a426c1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'normalized'), name='unique_spelling_word_per_user')],
            },
        ),
    ]
