# Generated by Django 5.2.14 on 2026-06-11 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0009_spellingdrillword_srs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellingDrillDailyBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_day', models.DateField()),
                ('word_ids', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spelling_drill_daily_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'review_day'], name='writing_sp_batch_user_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'review_day'), name='unique_spelling_daily_batch_per_user')],
            },
        ),
    ]
