# Generated by Django 5.2.14 on 2026-06-12 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0010_spelling_daily_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingFrameTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frame_key', models.CharField(max_length=120)),
                ('template_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_frame_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'frame_key'], name='writing_frame_user_key_idx'), models.Index(fields=['user', 'updated_at'], name='writing_frame_user_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'frame_key'), name='unique_writing_frame_template_per_user')],
            },
        ),
    ]
