# Generated by Django 5.2.14 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0011_writingframetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="spellingdrilldailybatch",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
