# Generated by Django 5.2.14 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0013_customwritingprompt_writingentry_custom_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="customwritingprompt",
            name="category",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
