from django.contrib import admin
from django.urls import path

from apps.accounts import views as account_views
from apps.ai import views as ai_views
from apps.billing import views as billing_views
from apps.common.views import frontend_asset, frontend_static_asset, health
from apps.speaking import views as speaking_views
from apps.writing import views as writing_views

urlpatterns = [
    path("", frontend_asset, name="frontend-index"),
    path("index.html", frontend_asset, name="frontend-index-html"),
    path("shared-ui.js", frontend_asset, {"asset_path": "shared-ui.js"}, name="frontend-shared-ui-js"),
    path("app.js", frontend_asset, {"asset_path": "app.js"}, name="frontend-app-js"),
    path("styles.css", frontend_asset, {"asset_path": "styles.css"}, name="frontend-styles-css"),
    path("assets/<path:asset_path>", frontend_static_asset, name="frontend-static-asset"),
    path("admin/", admin.site.urls),
    path("api/health/", health, name="health"),
    path("api/accounts/csrf/", account_views.csrf_token, name="account-csrf"),
    path("api/accounts/register/", account_views.register, name="account-register"),
    path("api/accounts/login/", account_views.login_view, name="account-login"),
    path("api/accounts/logout/", account_views.logout_view, name="account-logout"),
    path("api/accounts/me/", account_views.me, name="account-me"),
    path("api/accounts/password/change/", account_views.password_change, name="account-password-change"),
    path("api/accounts/password/reset/availability/", account_views.password_reset_availability, name="account-password-reset-availability"),
    path("api/ai/tasks/", ai_views.tasks, name="ai-tasks"),
    path("api/ai/tasks/<str:task_id>", ai_views.task_detail, name="ai-task-detail"),
    path("api/ai/tasks/<str:task_id>/cancel/", ai_views.task_cancel, name="ai-task-cancel"),
    path("api/history", speaking_views.history_view, name="speaking-history"),
    path("api/history/<str:attempt_id>", speaking_views.attempt_view, name="speaking-attempt"),
    path("api/attempts/start", speaking_views.attempt_start_view, name="attempts-start"),
    path("api/attempts/<str:attempt_id>/turns/<str:turn_id>/audio", speaking_views.turn_audio_upload_view, name="turn-audio-upload"),
    path("api/attempts/<str:attempt_id>/turns/<str:turn_id>/complete", speaking_views.turn_complete_view, name="turn-complete"),
    path("api/attempts/<str:attempt_id>/turns/<str:turn_id>/feedback/regenerate", speaking_views.turn_feedback_regenerate_view, name="turn-feedback-regenerate"),
    path("api/attempts/<str:attempt_id>/turns/<str:turn_id>/transcript/regenerate", speaking_views.turn_transcript_regenerate_view, name="turn-transcript-regenerate"),
    path("api/attempts/<str:attempt_id>/abort", speaking_views.attempt_abort_view, name="attempt-abort"),
    path("api/attempts/<str:attempt_id>/score", speaking_views.attempt_score_view, name="attempt-score"),
    path("api/audio/<str:attempt_id>/<str:turn_id>/candidate", speaking_views.turn_audio_candidate_view, name="turn-audio-candidate"),
    path("api/tts", speaking_views.tts_view, name="speaking-tts"),
    path("api/tts/warmup", speaking_views.tts_warmup_view, name="speaking-tts-warmup"),
    path("api/tts-audio/<str:role>/<str:filename>", speaking_views.tts_audio_view, name="speaking-tts-audio"),
    path("api/p3/questions", speaking_views.p3_view, name="speaking-p3-questions"),
    path("api/p3/follow-up", speaking_views.p3_follow_up_view, name="speaking-p3-follow-up"),
    path("api/reports/latest", speaking_views.latest_report_view, name="speaking-latest-report"),
    path("api/question-bank/summary", speaking_views.question_bank_summary_view, name="question-bank-summary"),
    path("api/question-bank/sample", speaking_views.question_bank_sample_view, name="question-bank-sample"),
    path("api/p1-corpus", speaking_views.p1_corpus_view, name="p1-corpus"),
    path("api/p2-corpus", speaking_views.p2_corpus_view, name="p2-corpus"),
    path("api/p2-corpus/<str:entry_id>", speaking_views.p2_corpus_detail_view, name="p2-corpus-detail"),
    path("api/language-takeaways", speaking_views.language_takeaway_view, name="language-takeaways"),
    path("api/language-takeaways/translate", speaking_views.language_takeaway_translate_view, name="language-takeaway-translate"),
    path("api/language-takeaways/<str:entry_id>", speaking_views.language_takeaway_detail_view, name="language-takeaway-detail"),
    path("api/writing-takeaways", speaking_views.writing_takeaway_view, name="writing-takeaways"),
    path("api/writing-takeaways/<str:entry_id>", speaking_views.writing_takeaway_detail_view, name="writing-takeaway-detail"),
    path("api/training/weak-items", speaking_views.training_weak_items_view, name="training-weak-items"),
    path("api/training/replay-queue", speaking_views.training_replay_queue_view, name="training-replay-queue"),
    path("api/billing/wallet", billing_views.wallet, name="billing-wallet-noslash"),
    path("api/billing/wallet/", billing_views.wallet, name="billing-wallet"),
    path("api/billing/recharge", billing_views.recharge, name="billing-recharge-noslash"),
    path("api/billing/recharge/", billing_views.recharge, name="billing-recharge"),
    path("api/billing/reservations", billing_views.reserve, name="billing-reserve-noslash"),
    path("api/billing/reservations/", billing_views.reserve, name="billing-reserve"),
    path("api/billing/reservations/release", billing_views.release, name="billing-release-noslash"),
    path("api/billing/reservations/release/", billing_views.release, name="billing-release"),
    path("api/billing/settle", billing_views.settle, name="billing-settle-noslash"),
    path("api/billing/settle/", billing_views.settle, name="billing-settle"),
    path("api/writing/summary", writing_views.summary, name="writing-summary"),
    path("api/writing/reports", writing_views.reports, name="writing-reports"),
    path("api/agent/writing/prompts/search", writing_views.agent_prompt_search, name="agent-writing-prompt-search"),
    path("api/writing/prompts", writing_views.prompts, name="writing-prompts"),
    path("api/writing/prompts/random", writing_views.random_prompt_view, name="writing-random-prompt"),
    path("api/writing/entries", writing_views.entries, name="writing-entries"),
    path("api/writing/entries/<str:entry_id>", writing_views.entry_detail, name="writing-entry-detail"),
    path("api/writing/entries/<str:entry_id>/clone", writing_views.entry_clone, name="writing-entry-clone"),
    path("api/writing/entries/<str:entry_id>/score", writing_views.entry_score, name="writing-entry-score"),
    path("api/writing/entries/<str:entry_id>/score-task", writing_views.entry_score_task, name="writing-entry-score-task"),
]
