# Generated by Django 5.2.14 on 2026-05-14 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_attempt_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('mode', models.CharField(choices=[('p1', 'Part 1'), ('p2', 'Part 2'), ('p3', 'Part 3'), ('mock', 'Mock')], max_length=16)),
                ('part', models.CharField(blank=True, max_length=16)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('started', 'Started'), ('ready_to_score', 'Ready to score'), ('scored', 'Scored'), ('aborted', 'Aborted')], default='started', max_length=32)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('english_name', models.CharField(blank=True, max_length=120)),
                ('target_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('fluency_coherence', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('lexical_resource', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('grammar_range_accuracy', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('pronunciation', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('feedback_summary', models.TextField(blank=True)),
                ('report_payload', models.JSONField(blank=True, default=dict)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='speaking.speakingattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turn_id', models.CharField(max_length=80)),
                ('sequence', models.PositiveIntegerField()),
                ('part', models.CharField(blank=True, max_length=16)),
                ('question', models.TextField()),
                ('transcript_raw', models.TextField(blank=True)),
                ('transcript_cleaned', models.TextField(blank=True)),
                ('transcript_source', models.CharField(blank=True, max_length=80)),
                ('audio_path', models.CharField(blank=True, max_length=500)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('counts_toward_total', models.BooleanField(default=True)),
                ('pronunciation', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='speaking.speakingattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_turns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='speakingattempt',
            index=models.Index(fields=['user', 'created_at'], name='speaking_sp_user_id_187bae_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingattempt',
            index=models.Index(fields=['user', 'mode', 'created_at'], name='speaking_sp_user_id_a26f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingattempt',
            index=models.Index(fields=['status', 'created_at'], name='speaking_sp_status_d86b93_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingreport',
            index=models.Index(fields=['user', 'created_at'], name='speaking_sp_user_id_b6c4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingreport',
            index=models.Index(fields=['overall_band', 'created_at'], name='speaking_sp_overall_4e0c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingturn',
            index=models.Index(fields=['user', 'created_at'], name='speaking_sp_user_id_935c41_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingturn',
            index=models.Index(fields=['attempt', 'sequence'], name='speaking_sp_attempt_c907bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='speakingturn',
            constraint=models.UniqueConstraint(fields=('attempt', 'turn_id'), name='unique_speaking_turn_per_attempt'),
        ),
    ]
