# Generated by Django 5.2.14 on 2026-05-14 14:57

import hashlib

from django.db import migrations, models


def populate_attempt_ids(apps, schema_editor):
    SpeakingAttempt = apps.get_model("speaking", "SpeakingAttempt")
    for attempt in SpeakingAttempt.objects.all().order_by("pk"):
        base = attempt.legacy_attempt_id or f"speaking-attempt-{attempt.pk}"
        digest = hashlib.sha1(f"{attempt.pk}:{base}".encode("utf-8")).hexdigest()[:20]
        attempt.attempt_id = str(attempt.legacy_attempt_id or f"attempt_{digest}")[:80]
        attempt.save(update_fields=["attempt_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0002_speakingtrainingobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingattempt',
            name='attempt_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.RunPython(populate_attempt_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='speakingattempt',
            name='attempt_id',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
    ]
