# Generated by Django 5.2.14 on 2026-05-17 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0003_speakingattempt_attempt_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='P1CorpusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_id', models.CharField(max_length=160)),
                ('topic', models.CharField(blank=True, max_length=120)),
                ('question', models.TextField()),
                ('corpus_text', models.TextField(blank=True)),
                ('last_ai_answer', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_corpus_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'topic'], name='speaking_p1_user_topic_idx'), models.Index(fields=['user', 'updated_at'], name='speaking_p1_user_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'question_id'), name='unique_p1_corpus_question_per_user')],
            },
        ),
    ]
