# Generated by Django 5.2.14 on 2026-05-17 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0004_p1corpusentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='P2CorpusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_id', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('person', '人物'), ('place', '地点'), ('event', '事件'), ('object', '物品'), ('special', '特殊题目')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('material_text', models.TextField(blank=True)),
                ('linked_question', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_corpus_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'category'], name='speaking_p2_user_category_idx'), models.Index(fields=['user', 'updated_at'], name='speaking_p2_user_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'entry_id'), name='unique_p2_corpus_entry_per_user')],
            },
        ),
    ]
