# Generated by Django 5.2.15 on 2026-06-06 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0006_languagetakeawayentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='P2BankCorpusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_id', models.CharField(max_length=160)),
                ('question', models.TextField()),
                ('corpus_text', models.TextField(blank=True)),
                ('last_ai_answer', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_bank_corpus_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'updated_at'], name='speak_p2bank_user_upd_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'question_id'), name='unique_p2_bank_corpus_question_per_user')],
            },
        ),
        migrations.CreateModel(
            name='P3BankFollowupCorpusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('p2_question_id', models.CharField(max_length=160)),
                ('followup_id', models.CharField(max_length=200)),
                ('followup_question', models.TextField()),
                ('corpus_text', models.TextField(blank=True)),
                ('last_ai_answer', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p3_bank_followup_corpus_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'p2_question_id'], name='speaking_p3bank_user_p2_idx'), models.Index(fields=['user', 'updated_at'], name='speak_p3bank_user_upd_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'followup_id'), name='unique_p3_bank_followup_per_user')],
            },
        ),
    ]
