# Generated by Django 5.2.14 on 2026-06-12 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0008_takeawayreviewstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionReplacementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('language', 'Language'), ('writing', 'Writing')], max_length=16)),
                ('item_id', models.CharField(max_length=160)),
                ('source', models.TextField(blank=True)),
                ('replacements', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expression_replacement_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'kind'], name='speaking_expr_user_kind_idx'), models.Index(fields=['user', 'updated_at'], name='speaking_expr_user_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'item_id'), name='unique_expression_replacement_per_user_kind')],
            },
        ),
    ]
