# Generated by Django 5.2.14 on 2026-05-14 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodexUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_id', models.CharField(max_length=80, unique=True)),
                ('call_id', models.CharField(max_length=160, unique=True)),
                ('provider', models.CharField(default='codex', max_length=80)),
                ('model', models.CharField(default='codex-cli', max_length=120)),
                ('raw_jsonl_path', models.CharField(blank=True, max_length=500)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('cached_input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('reasoning_output_tokens', models.PositiveIntegerField(default=0)),
                ('raw_usage', models.JSONField(blank=True, default=dict)),
                ('semantics_version', models.CharField(default='codex_cli_json_v1', max_length=80)),
                ('captured_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_id', models.CharField(max_length=80, unique=True)),
                ('model', models.CharField(max_length=120)),
                ('input_price_u_per_1m_tokens', models.BigIntegerField()),
                ('cached_input_price_u_per_1m_tokens', models.BigIntegerField()),
                ('output_price_u_per_1m_tokens', models.BigIntegerField()),
                ('reasoning_price_u_per_1m_tokens', models.BigIntegerField(default=0)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(max_length=120)),
            ],
            options={
                'indexes': [models.Index(fields=['model', 'effective_from'], name='billing_pri_model_3abea3_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_u', models.BigIntegerField(default=0)),
                ('reserved_u', models.BigIntegerField(default=0)),
                ('carry_numerator_u', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=24)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=80, unique=True)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_order_id', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('amount_u', models.BigIntegerField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='billing_pay_user_id_0aafb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_id', models.CharField(max_length=80, unique=True)),
                ('call_id', models.CharField(blank=True, max_length=160)),
                ('entry_type', models.CharField(choices=[('grant', 'Grant'), ('reserve', 'Reserve'), ('settle', 'Settle'), ('release', 'Release'), ('adjust', 'Adjust'), ('refund', 'Refund'), ('recharge', 'Recharge')], max_length=24)),
                ('amount_u', models.BigIntegerField()),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.pricesnapshot')),
                ('usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.codexusageevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='billing_wal_user_id_1a67df_idx'), models.Index(fields=['call_id'], name='billing_wal_call_id_016d11_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_id', models.CharField(max_length=80, unique=True)),
                ('call_id', models.CharField(max_length=160, unique=True)),
                ('reserved_u', models.BigIntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('released', 'Released'), ('settled', 'Settled'), ('expired', 'Expired')], default='reserved', max_length=24)),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='billing_wal_user_id_efff82_idx'), models.Index(fields=['status', 'created_at'], name='billing_wal_status_4f53e6_idx')],
            },
        ),
    ]
