# Generated by Django 5.2.14 on 2026-05-14 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(max_length=80)),
                ('provider', models.CharField(default='codex', max_length=80)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('fallback', 'Fallback')], default='pending', max_length=24)),
                ('related_type', models.CharField(blank=True, max_length=80)),
                ('related_id', models.CharField(blank=True, max_length=80)),
                ('prompt_version', models.CharField(blank=True, max_length=80)),
                ('fallback_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'task_type', 'status', 'created_at'], name='ai_aitask_user_id_95afea_idx'), models.Index(fields=['related_type', 'related_id'], name='ai_aitask_related_3f41a8_idx')],
            },
        ),
    ]
