# Generated by Django 5.2.14 on 2026-05-14 23:37

import hashlib
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_task_ids(apps, schema_editor):
    ai_task = apps.get_model("ai", "AITask")
    for task in ai_task.objects.filter(task_id__isnull=True):
        seed = f"{task.user_id}:{task.idempotency_key}" if task.idempotency_key else f"{task.user_id}:{task.task_type}:{task.related_type}:{task.related_id}:{uuid.uuid4().hex}"
        task.task_id = f"aitask_{hashlib.sha1(seed.encode('utf-8')).hexdigest()[:24]}"
        task.save(update_fields=["task_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('billing', '0002_legacybillinguser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aitask',
            name='available_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='aitask',
            name='billing_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_tasks', to='billing.walletreservation'),
        ),
        migrations.AddField(
            model_name='aitask',
            name='call_id',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name='aitask',
            name='error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aitask',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aitask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aitask',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aitask',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='aitask',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aitask',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aitask',
            name='result_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aitask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aitask',
            name='task_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aitask',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_tasks', to='billing.codexusageevent'),
        ),
        migrations.AddField(
            model_name='aitask',
            name='worker_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(backfill_task_ids, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['user', 'status', 'available_at'], name='ai_aitask_user_id_927ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['call_id'], name='ai_aitask_call_id_bba161_idx'),
        ),
    ]
