# Generated by Django 5.2.15 on 2026-06-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_legacy_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='report_ai_source',
            field=models.CharField(choices=[('gpt', 'GPT (默认)'), ('claude_cli', 'Claude CLI')], default='gpt', max_length=32),
        ),
    ]
