# Generated by Django 5.2.14 on 2026-06-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_report_ai_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='report_ai_source',
            field=models.CharField(choices=[('gpt', 'GPT (默认)'), ('claude', 'Claude'), ('claude_cli', 'Claude CLI')], default='gpt', max_length=32),
        ),
    ]
