# Generated by Django 5.2.14 on 2026-06-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_report_ai_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='report_ai_source',
            field=models.CharField(choices=[('gpt', 'GPT (默认)'), ('claude', 'Claude Sonnet'), ('claude_haiku', 'Claude Haiku'), ('claude_cli', 'Claude CLI (Sonnet)'), ('claude_cli_haiku', 'Claude CLI (Haiku)')], default='gpt', max_length=32),
        ),
    ]
